language: python

python:
  - 3.6
  - nightly

install:
  - pip install pipenv
  - pipenv install
  - pip install -r requirements.txt

script:
  - python manage.py test -c

after_success:
  - bash <(curl -s https://codecov.io/bash)